database/models/cliente.py
from peewee import Model, CharField, DateTimeField
from database.database import db
import datetime

class Cliente(Model):
    nome = CharField()
    email = CharField()
    data_registro = DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db

main.py
from flask import Flask
from configure import configure_all



app = Flask(__name__)

configure_all(app)

app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request

import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))



from database.models.cliente import Cliente


cliente_route = Blueprint('clientes', __name__)

@cliente_route.route('/')
def lista_cliente():
    """ listar os clientes """
    clientes= Cliente.select()
    print('lista_clientes: ', clientes)
    return render_template('lista_cliente.html', clientes= clientes)


@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    """  inserir os dados do usuário """
    data = request.json

    novo_usuario = Cliente.create(
        nome = data['nome'],
        email = data['email']
    )

    return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente():
    """ formulario para cadastrar os clientes """
    return render_template('form_cliente.html')


@cliente_route.route('/<int:cliente_id>')
def detalhe_usuário(cliente_id):
    """formulario para detalhes dos dados do usuário"""

    cliente = Cliente.get_by_id(cliente_id)
    return render_template('detalhe_usuario.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_usuário(cliente_id):
    """formulario para editar os dados do cliente"""

    cliente = Cliente.get_by_id(cliente_id)

    return render_template('form_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_usuario(cliente_id):
    """formulario para atualizar os dados do cliente"""

    data = request.json
    cliente_editado= None
    
    cliente_editado = Cliente.get_by_id
    (cliente_id)
    cliente_editado.nome = data['nome']
    cliente_editado.email = data['email']
    cliente_editado.save()
    #editar usuario
    return render_template('item_cliente.html', cliente= cliente_editado)

    #editar usuario
   
   


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_usuario(cliente_id):
    """formulario para deletar os dados do cliente"""
    cliente = Cliente.get_by_id(cliente_id)
    (cliente_id)
    cliente.delete_instance()
    
    return {"deleted": "ok"}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/detalhe_usuario.html
<ul>
    <li>ID:{{ cliente.id }}</li>
    <li>Nome:{{ cliente.nome }}</li>
    <li>Email:{{ cliente.email }}</li>
</ul>

templates/form_cliente.html
<form class="c-form" 
      {% if cliente %}
            action="{{ url_for('clientes.atualizar_usuario', cliente_id=cliente.id)}}" 
      {% else %}
            action="{{ url_for('clientes.inserir_cliente')}}" 
      {% endif %}


      method="{% if cliente %}PUT{% else %}POST{% endif %}" 

      {% if cliente %}
        c-swap="#cliente-{{cliente.id}}"

      {% else %}
          c-append="#lista-clientes"
      {% endif %}
      
      c-reload-container="True">

    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome" {% if cliente %}value="{{cliente.nome}}"{% endif%}>
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="text" class="form-control" name="email" name="nome" {% if cliente %}value="{{cliente.email}}"{% endif%}>
    </div>



    <button type="submit" class="btn btn-primary">
      {% if cliente %}Salvar{% else %}Criar{% endif %}
    </button>
</form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>USER</title>
    <link rel="shortcut icon" href="https://icons.iconarchive.com/icons/simpleicons-team/simple/256/flask-icon.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css' ) }}">

  </head>
  <body>

  <div class="container">

    <h1 class="text-center">Gestão de Usuários</h1>


    <!-- formulario para criar clientes-->
    <div id="form-cliente" 
    c-container="{{ url_for('clientes.form_cliente') }}"></div>

    <hr>

    <h2>Lista dos clientes</h2>
    <!-- lista de clientes-->
    <div c-container="{{ url_for('clientes.lista_cliente') }}" ></div>
  </div>
  
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="exibir-cliente">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js' ) }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>


    <td>

        <button class="btn btn-secondary" 
            c-get="{{ url_for('clientes.detalhe_usuário', cliente_id=cliente.id) }}"
            c-target="#exibir-cliente"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
            VER</button>


        <button class="btn btn-primary" 
            c-get="{{ url_for('clientes.form_edit_usuário', cliente_id=cliente.id) }}"
            c-target="#form-cliente">
            EDITAR</button>



        <button class="btn btn-danger"
            c-delete="{{ url_for('clientes.delete_usuario', cliente_id = cliente.id) }}"
            c-remove-closest="tr">
            DELETAR</button>
    </td>


</tr>

templates/lista_cliente.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">

      {% for cliente in clientes %}
          {% include 'item_cliente.html' %}
      {% endfor %}

    </tbody>
  </table>